import turtle
mypen = turtle.Turtle()
mypen.penup()
mypen.forward(100)
mypen.down()

mypen.color("black")
mypen.right(90)
mypen.left(180)
mypen.forward(500)
mypen.left(90)
mypen.forward(250)
mypen.left(90)
mypen.forward(500)
mypen.left(90)
mypen.forward(250)

mypen.penup()
mypen.goto(-25,385)
mypen.down()
mypen.color("green")
mypen.circle(50)

mypen.penup()
mypen.goto(-25,215)
mypen.down()
mypen.color("yellow")
mypen.circle(50)

mypen.penup()
mypen.goto(-25,65)
mypen.down()
mypen.color("red")
mypen.circle(50)